# Copyright 2025 Jiaqi Liu. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Antiqua CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10"
  NEO4J_ENTERPRISE_VERSION: 5.24-enterprise
  NEO4J_URI: neo4j://localhost:7687
  NEO4J_DATABASE: neo4j
  NEO4J_USERNAME: not used
  NEO4J_PASSWORD: not used

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd #v3.0.1

  code-style:
    name: Python Code Style Check
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python 3.10
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Check import orders
        run: isort --check .
      - name: pep8
        run: pycodestyle .

  unit-tests:
    name: Unit Tests
    needs: [code-style, pre-commit]
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run tests
        run: python -m unittest

  sync-to-huggingface-space:
    needs: unit-tests
    name: Sync with Hugging Face Datasets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Generate Hugging Face Datasets
        run: |
          cd huggingface
          python3 ./generate_datasets.py
      - name: Push to hub
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name "QubitPi"
          git config --global user.email "jack20220723@gmail.com"

          git clone https://QubitPi:"$HF_TOKEN"@huggingface.co/datasets/QubitPi/Antiqua
          cd Antiqua
          rm -rf ./*
          mv ../huggingface/README.md .
          mv ../*-graph-data.jsonl .

          git lfs install
          git lfs track "./*-graph-data.jsonl"
          git add .
          git add ./*-graph-data.jsonl

          git commit -m "Generate Hugging Face Datasets"
          git push -f
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

  docker:
    name: Test Docker Build and Publish Data Image to DockerHub
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Startup a Neo4J database
        run: |
          docker run \
              --publish=7474:7474 \
              --publish=7687:7687 \
              --env=NEO4J_AUTH=none \
              --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
              -e NEO4JLABS_PLUGINS=\[\"apoc\"\] \
              --name data-loader \
              neo4j:${{ env.NEO4J_ENTERPRISE_VERSION }} &
      - name: Wait for database to be ready
        uses: iFaxity/wait-on-action@a7d13170ec542bdca4ef8ac4b15e9c6aa00a6866 # v1.2.1
        with:
          resource: http://localhost:7474
      - name: Load all languages into the intermediate container
        run: |
          cd graph-database-loader
          pip3 install -r requirements.txt
          pip3 install -e .
          python3 wilhelm_vocabulary/load_all_in_parallel.py
        env:
          NEO4J_URI: ${{ env.NEO4J_URI }}
          NEO4J_DATABASE: ${{ env.NEO4J_DATABASE }}
          NEO4J_USERNAME: ${{ env.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ env.NEO4J_PASSWORD }}
      - name: Copy over data onto host
        run: docker cp data-loader:/data .
      - name: Test image build
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          push: false
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: jack20191124
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: .
          push: true
          tags: jack20191124/antiqua:latest
      - name: Push image Description
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: jack20191124
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: jack20191124/antiqua
          readme-filepath: README.md

  cleanup-neo4j:
    needs: unit-tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: graph-database-loader
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cleanup
        run: |
          pip3 install -e .
          python3 wilhelm_vocabulary/cleanup_neo4j.py
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_DATABASE: ${{ secrets.NEO4J_DATABASE }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

  load-vocabulary:
    name: Load ${{ matrix.language.name }} vocabularies
    defaults:
      run:
        working-directory: graph-database-loader
    needs: cleanup-neo4j
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [
          {
            name: German,
            load-script: wilhelm_vocabulary/load_german.py
          },
          {
            name: Ancient Greek,
            load-script: wilhelm_vocabulary/load_ancient_greek.py
          },
          {
            name: Latin,
            load-script: wilhelm_vocabulary/load_latin.py
          }
        ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Load ${{ matrix.language.name }}
        run: |
          pip3 install -e .
          python3 ${{ matrix.language.load-script }}
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_DATABASE: ${{ secrets.NEO4J_DATABASE }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}

#  triggering:
#    name: Triggering data loader CI/CD
#    needs: [sync-to-huggingface-space, docker]
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Trigger graph-database-loader to load all vocabularies into graph database
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.QUBITPI_DOWNSTREAM_CICD_TRIGGERING_TOKEN }}
#          repository: QubitPi/antiqua-acceptance-tests
#          event-type: antiqua-changes
